name: ci/cd pipeline
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout File
      uses: actions/checkout@v4
    
    - name: Setup python
      uses: action/setup-python@v4
      with: 
        python-version: 3.9

    - name: install dependicies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: train model
      run: python random_fr.py

    - name: upload artifact model
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: random_forest.pkl

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
    - name: Checkoutfiles
      uses: actions/checkout@v4
    
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: model-artifact
        path: .
    - name: Docker image build
      run: docker build -t ml-flask-app
    - name: run docker cointainer
      run: docker run -d -p 5000:5000 --name ml-container ml-flask-app
     