name: CI/CD pipeline
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkput files
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependicies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: train model
      run: python random_fr.py

    - name: upload artifact model
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: random_forest.pkl

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
    
    - name: checkoutFiles
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifact
        path: .

    - name: Docker image Build
      run: docker build -t ml-flask-app .
    
    - name: docekr container run
      run: docker run -d -p 5000:5000 --name ml-flask ml-flask-app
